# Generated by Django 4.0.3 on 2022-04-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
