# Generated by Django 4.0.3 on 2022-04-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algus', '0004_alter_produtos_options_produtos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
