# Generated by Django 4.0.3 on 2022-04-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algus', '0007_vendidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendidos',
            name='data',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
